README.md

Update readme package download link

---

README.md

- Moved section from "Authentication" to "Authorization" and made it more clear.

Updated readme "Authorization on an endpoint"

---

README.md
src/config.ts
src/controllers.ts
src/types.ts

- Removes FRONTEND_PORT, PORT, and ENVIRONMENT env variables.
- Adds guard and debug statements to KCOptions afterUserLogin and afterUserLogout functions.

Updated config, updated KCOptions

---

src/controllers.ts

Fix KCOptions

---

src/index.ts

[Issue #6](https://github.com/bcgov/citz-imb-kc-express/issues/6)
Init log message only shows in DEBUG mode now

Init log message only shows in DEBUG mode now

---

src/config.ts

Fixed debug variable

---

src/middleware.ts

Removing ability to use string for roles parameter instead of string array.

Tweak protectedRoute

---

README.md
src/middleware.ts

Errors if req.user cannot be set

Errors if req.user cannot be set

---

package.json
src/controllers.ts
src/utils/kcApi.ts

- Added refresh token expiry to login redirect query params (will be used in frontend)
- Adjusted build script

Added refresh expiry to login response

---

.github/workflows/release.yaml

[MVP-74](https://citz-imb.atlassian.net/jira/browse/MVP-74)
Added workflow for release from react package

MVP-74: Updated release github workflow

---

.github/workflows/release.yaml
README.md
package.json

[MVP-15](https://citz-imb.atlassian.net/jira/browse/MVP-15)
- Copy of react package which is working!

MVP-15: NPM Publish on Release Action

---

package.json

[MVP-76](https://citz-imb.atlassian.net/jira/browse/MVP-76)
Updated packages

MVP-76: Updated packages

---

README.md
src/controllers.ts
src/middleware.ts
src/types.ts
src/utils/debug.ts
src/utils/user.ts

[MVP-84](https://citz-imb.atlassian.net/jira/browse/MVP-84)
Changes `req.user` to a normalized version of the user objects defined by sso.
`req.userInfo` is now a combined user object with properties such as `idir_user_guid` and `bceid_user_guid` where as `req.user` now combines both of these into a `guid` property.
Here is an example of this new normalized user as `KeycloakUser` type (the old type is now CombinedKeycloakUser):
``` JSON
{
"guid": "W7802F34D2390EFA9E7JK15923770279",
"preferred_username": "a7254c34i2755fea9e7ed15918356158@idir",
"username": "JOHNDOE",
"email": "john.doe@gov.bc.ca",
"name": "Doe, John CITZ:EX",
"display_name": "Doe, John CITZ:EX",
"first_name": "John",
"last_name": "Doe",
"client_roles": ["Admin"],
"scope": "openid idir email profile azureidir", …
```

MVP-84: Normalized user object

---

.github/workflows/release.yaml
README.md
package.json
src/config.ts
src/controllers.ts
src/index.ts
src/router.ts
src/types.ts
src/utils/debug.ts
src/utils/user.ts

[MVP-117](https://citz-imb.atlassian.net/jira/browse/MVP-117)
- Renamed from `kc` and `keycloak` to `sso`

MVP-117: Rename to SSO

---

README.md
src/controllers.ts
src/middleware.ts
src/types.ts
src/utils/debug.ts
src/utils/user.ts

[MVP-120](https://citz-imb.atlassian.net/jira/browse/MVP-120)
- Renamed `CombinedSSOUser` to `OriginalSSOUser`
- Added `OriginalSSOUser` to `SSOUser` as `originalData`

MVP-120: Refactored user type

---

src/types.ts
src/utils/user.ts

[MVP-124](https://citz-imb.atlassian.net/jira/browse/MVP-124)
- Added `hasRoles` to `req.user` object.
- Updated Wiki

MVP-124: Added hasRoles to user object

---

README.md
package.json

Updating version to 1.0.0-alpha

---

src/config.ts

[MVP-130](https://citz-imb.atlassian.net/jira/browse/MVP-130)

MVP-130: Throw error if env vars arent set

---

package.json
src/config.ts
src/controllers.ts
src/utils/debug.ts

- Updated to `alpha2`
- Added debug statements
Tested in `CoCo` app

Alpha2: Added debug statements

---

src/config.ts

[MVP-144](https://citz-imb.atlassian.net/jira/browse/MVP-144)
Sets the default value for `COOKIE_DOMAIN` to `localhost` if `FRONTEND_URL` includes `localhost`, otherwise it sets to `.gov.bc.ca`
- Updated Wiki Env vars

MVP-144: Modified default for COOKIE_DOMAIN

---

package.json

Updated to alpha 3

---

package.json
src/config.ts

[MVP-144](https://citz-imb.atlassian.net/jira/browse/MVP-144)
The cookie issue was fixed in dev when we used version `alpha2` but switching to `alpha3` broke it again. The only difference between the 2 versions is that `COOKIE_DOMAIN` was set to `.gov.bc.ca` by default in `alpha2` and then extra logic was added in `alpha3` to try and make it work in local.

MVP-144: Fix cookie issue

---

package.json
src/config.ts

[MVP-144](https://citz-imb.atlassian.net/jira/browse/MVP-144)
I was still setting a default value so it never had a chance to meet the condition that would set it to 'localhost'
- Added debug statement to print config vars

MVP-144: Fix config issue

---

package.json

Was causing `Create Release` action to fail because it exits with exit code 1

Removed npm audit from pack command

---

package.json

[MVP-172](https://citz-imb.atlassian.net/jira/browse/MVP-172)
ESLint works and package builds without errors.

MVP-172: Dependency updates

---

docs/test.txt

[MVP-181](https://citz-imb.atlassian.net/browse/MVP-181)
Need a folder to host the devhub documentation.

MVP-181 Add Devhub Documentation Folder

---

.gitignore
__tests__/utils/authUrls.test.ts
__tests__/utils/debug.test.ts
__tests__/utils/jwt.test.ts
__tests__/utils/kcApi.test.ts
__tests__/utils/user.test.ts
jest.config.ts
package.json
tsconfig.json

[MVP-139](https://citz-imb.atlassian.net/jira/browse/MVP-139)
- Added jest packages and config
- Updates to `tsconfig`
- Added unit tests for utils

MVP-139: Part1 Adding unit tests

---

.eslintrc.cjs
.prettierignore
README.md
tsconfig.json

- Fixed tsconfig because package imports were not working

Readme additions and ignore coverage

---

README.md
tsconfig.json

- Readme changes
- Fix tests not running because jest config needed jsonResolveModule

Readme changes

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

[MVP-217](https://citz-imb.atlassian.net/jira/browse/MVP-217)
Added bug report and feature request issue templates

MVP-217: Added issue templates

---

mkdocs.yml
techdocs/docs/getting-started/environment-variables.md
techdocs/docs/getting-started/quick-start-guide.md
techdocs/docs/index.md
techdocs/docs/purpose-and-benefits.md
techdocs/docs/using-the-package/environment-variables.md
techdocs/docs/using-the-package/typescript-types.md

[MVP-238](https://citz-imb.atlassian.net/browse/MVP-238)
Updating formatting and links of techdocs. 
To see changes in place please reference: https://dev.developer.gov.bc.ca/docs/default/component/citz-imb-sso-express-npm-package/

MVP-238 Refining Techdocs

---

jest.config.ts
mkdocs.yml
techdocs/docs/using-the-package/troubleshooting.md

[MVP-240](https://citz-imb.atlassian.net/jira/browse/MVP-240)
You can view the changes here: https://dev.developer.gov.bc.ca/docs/default/component/citz-imb-sso-express-npm-package/using-the-package/troubleshooting/

MVP-240: Added Troubleshooting techdoc page

---

.github/workflows/publish-techdocs.yaml

creating this change such that documentation will be build on prod devhub

Techdoc Workflow Publish on Merge to Main

---

techdocs/docs/index.md

[MVP-](https://citz-imb.atlassian.net/jira/browse/MVP-)

Update index.md triggering publish action

---

.github/workflows/publish-techdocs.yaml
techdocs/docs/index.md

Adding change to workflow

---

.github/workflows/release.yaml

[MVP-245](https://citz-imb.atlassian.net/jira/browse/MVP-245)
Workflow tested in SSO React package repo.

MVP-245: Updated release workflow

---

README.md

[MVP-264](https://citz-imb.atlassian.net/jira/browse/MVP-264)

MVP-264: Updated documentation links in README

---

package.json
rollup.config.mjs
src/index.ts
src/utils/checkForUpdates.ts
src/utils/index.ts
tsconfig.json

[MVP-269](https://citz-imb.atlassian.net/jira/browse/MVP-269)
Added update notification on server startup
- Updated to version `1.0.0` so we can trigger the release action and create `1.0.0-beta`

MVP-269: update notification

---

README.md

[MVP-279](https://citz-imb.atlassian.net/jira/browse/MVP-279)

MVP-279: Updated links in README

---

techdocs/docs/index.md

[MVP-271](https://citz-imb.atlassian.net/jira/browse/MVP-271)
View @ https://dev.developer.gov.bc.ca/docs/default/component/citz-imb-sso-express-npm-package

MVP-271: Added package management plan link

---

scripts/bump-version.mjs

[MVP-245](https://citz-imb.atlassian.net/jira/browse/MVP-245)

MVP-245: Forgot to update bump script

---

.github/workflows/ci-unit-integration-test.yaml

[MVP-267](https://citz-imb.atlassian.net/jira/browse/MVP-267)

MVP-267: Create CI Action to Run Test Suite on PR Open

---

.github/workflows/test-coverage-report.yaml

[MVP-267](https://citz-imb.atlassian.net/jira/browse/MVP-267)

MVP-267: Create Test Coverage Report and Upload to Code Climate

---

jest.config.ts

[MVP-267](https://citz-imb.atlassian.net/jira/browse/MVP-267)

MVP-267: Update jest.config.ts

---

README.md

[MVP-267](https://citz-imb.atlassian.net/jira/browse/MVP-267)

MVP-267: Code Climate Badges

---

.github/workflows/publish-techdocs.yaml

[MVP-275](https://citz-imb.atlassian.net/jira/browse/MVP-275)
It was only picking up changes in the docs directory and not in subdirectories.

MVP-275: Update publish-techdocs.yaml

---

mkdocs.yml
src/types.ts
techdocs/docs/getting-started/quick-start-guide.md
techdocs/docs/using-the-package/apis-&-components/has-roles.md
techdocs/docs/using-the-package/apis-&-components/protected-route.md
techdocs/docs/using-the-package/apis-&-components/req-user.md
techdocs/docs/using-the-package/apis-&-components/sso.md
techdocs/docs/using-the-package/getting-user-information.md
techdocs/docs/using-the-package/init-options.md
techdocs/docs/using-the-package/protecting-a-route.md
techdocs/docs/using-the-package/typescript-types.md

[MVP-275](https://citz-imb.atlassian.net/jira/browse/MVP-275)
View @ https://dev.developer.gov.bc.ca/docs/default/component/citz-imb-sso-express-npm-package/

MVP-275: Added sso docs

---

mkdocs.yml
techdocs/docs/major-release-1.md
techdocs/docs/major-releases/major-release-1.md

[MVP-273](https://citz-imb.atlassian.net/jira/browse/MVP-273)
- Added Major Releases page in techdocs
https://dev.developer.gov.bc.ca/docs/default/component/citz-imb-sso-express-npm-package/

MVP-273: Added Major releases page

---

.github/helpers/techdocs/update-main-typescript-types.cjs
.github/helpers/techdocs/update-typescript-types.cjs
.github/workflows/document-techdoc-types.yaml
.github/workflows/publish-techdocs.yaml
techdocs/docs/getting-started/quick-start-guide.md
techdocs/docs/using-the-package/apis-&-components/has-roles.md
techdocs/docs/using-the-package/apis-&-components/protected-route.md
techdocs/docs/using-the-package/apis-&-components/req-user.md
techdocs/docs/using-the-package/apis-&-components/sso.md
techdocs/docs/using-the-package/typescript-types.md

[MVP-300](https://citz-imb.atlassian.net/jira/browse/MVP-300)
Scripts that run on push of source code. If the typescript types change, they will be updated where they are referenced in the docs.
Scripts can be run locally to test. Change the content of the typescript code blocks and run the script to watch it update them.

MVP-300: Automated type docs

---

techdocs/docs/using-the-package/apis-&-components/has-roles.md
techdocs/docs/using-the-package/apis-&-components/protected-route.md
techdocs/docs/using-the-package/apis-&-components/sso.md

[MVP-275](https://citz-imb.atlassian.net/jira/browse/MVP-275)
Same as requested for the css api component docs.
https://dev.developer.gov.bc.ca/docs/default/component/citz-imb-sso-express-npm-package/

MVP-275: Techdoc Formatting Changes

---

.codeclimate.yaml

[MVP-346](https://citz-imb.atlassian.net/jira/browse/MVP-346)

MVP-346: Add Code Climate Config

---

.codeclimate.yaml

[MVP-353](https://citz-imb.atlassian.net/jira/browse/MVP-353)

MVP-353: Add Plugins to Code Climate Config

---

package.json

[MVP-322](https://citz-imb.atlassian.net/jira/browse/MVP-322)

NPM-322-NPM-dependency-updates

---

__tests__/controllers/loginCallback.test.ts
src/controllers/loginCallback.ts

[MVP-360](https://citz-imb.atlassian.net/jira/browse/MVP-360)

MVP-360: Added sameSite attribute to refresh token cookie

---

.github/workflows/release.yaml

[MVP-370](https://citz-imb.atlassian.net/jira/browse/MVP-370)
Fixed the step of the Release workflow that creates a Github release.

MVP-370: Fixed release workflow

---

__tests__/controllers/logoutCallback.test.ts
src/controllers/logoutCallback.ts

[MVP-430](https://citz-imb.atlassian.net/jira/browse/MVP-430)
I think the cookie wasn't being cleared because we changed the settings on the original cookie but not the logout cookie clear.

MVP-430: Fix logout cookie issue

---

__tests__/controllers/logout.test.ts
src/controllers/logout.ts

Adds a fallback when id token is undefined on logout that will clear the refresh token and return to frontend.

Added fallback case for logout without id token

---

src/controllers/logout.ts

Updated fix for logout issue
